/**
 * Holds the classes that implement the program finite state machine.
 * The finite state machine acts as a broker between the model (the
 * logical representation of the program) and the view (the fxml and
 * the controllers). The user entirely interacts with the program
 * finite state machine, or another fsm (such as the photofsm or the
 * slideshowfsm) that was dynamically generated by the programfsm.
 */
package controller.programfsm;